server:
  port: 8080
spring:
  application:
    name: mbp-generator
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/generator?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level: {com: "debug"}
